[package]
name = "recat-adapter"
description = "recat infrastructure layer"
authors.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
